TRUNCATE TABLE verb;
INSERT INTO verb (verb_base_form, verb_past_simple, verb_past_participle, verb_continuous_form)
VALUES
       ('Engage', 'engaged', 'engaged', 'engaging'),
       ('Enhance', 'enhanced', 'enhanced', 'enhancing'),
       ('Participate', 'participated', 'participated', 'participating'),
       ('Assure', 'assured', 'assured', 'assuring'),
       ('Overcome', 'overcame', 'overcome', 'overcoming'),
       ('Owe', 'owed', 'owed', 'owing'),
       ('Suffer', 'suffered', 'suffered', 'suffering'),
       ('Acquire', 'acquired', 'acquired', 'acquiring'),
       ('Adjust', 'adjusted', 'adjusted', 'adjusting'),
       ('Throw', 'threw', 'thrown', 'throwing'),

       ('Abandon', 'abandoned', 'abandoned', 'abandoning'),
       ('Relieve', 'relieved', 'relieved', 'relieving'),
       ('Qualify', 'qualified', 'qualified', 'qualifying'),
       ('Retire', 'retired', 'retired', 'retiring'),
       ('Attach', 'attached', 'attached', 'attaching'),
       ('Convince', 'convinced', 'convinced', 'convincing'),
       ('Imply', 'implied', 'implied', 'implying'),
       ('Insist', 'insisted', 'insisted', 'insisting'),
       ('Accuse', 'accused', 'accused', 'accusing'),
       ('Specify', 'specified', 'specified', 'specifying'),

       ('Reflect', 'reflected', 'reflected', 'reflecting'),
       ('Justify', 'justified', 'justified', 'justifying'),
       ('Compete', 'competed', 'competed', 'competing'),
       ('Negotiate', 'negotiated', 'negotiated', 'negotiating'),
       ('Weight', 'weighted', 'weighted', 'weighting'),
       ('Establish', 'established', 'established', 'establishing'),
       ('Pursue', 'pursued', 'pursued', 'pursuing'),
       ('Warn', 'warned', 'warned', 'warning'),
       ('Announce', 'announced', 'announced', 'announcing'),
       ('Approve', 'approved', 'approved', 'approving');